name: Node.js CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        # cache: 'npm'
    - run: |
          npm install
          git add package-lock.json
          git commit -as -m "Add npm lockfile"
    - run: |
          npm run build --if-present
          ls -lAogR build/
          tree -h -I node_modules -L 5
          git add build
          git commit -as -m "Add Debug Release Files"
    - run: |
          npm run prod --if-present
          ls -lAogR prod/
          tree -h -I node_modules -L 5
          git add prod
          git commit -as -m "Add Production Release Files"
          git push
