name: Node.js CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'npm'
    - run: |
          npm ci
    - run: |
          npm run build --if-present
          npm run prod --if-present
          ls -lAogR build/ prod/
          tree -h -I node_modules -L 5
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add package-lock.json build prod
          git commit -as -m "Update Release Files"
          git push
